poed: update recipe to actually build something
The poed did not actually build anything, causing it generate no
packages since there was nothing to package. This later failed the image
generation as there was no poed package to install:

ERROR: dentos-image-1.0-r0 do_rootfs: Could not invoke dnf. Command '/home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/recipe-sysroot-native/usr/bin/dnf -v --rpmverbosity=info -y -c /home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/rootfs/etc/dnf/dnf.conf --setopt=reposdir=/home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/rootfs/etc/yum.repos.d --installroot=/home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/rootfs --setopt=logdir=/home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/temp --repofrompath=oe-repo,/home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/oe-rootfs-repo --nogpgcheck install packagegroup-core-boot packagegroup-dentos run-postinsts' returned 1:
DNF version: 4.21.1
cachedir: /home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/rootfs/var/cache/dnf
Added oe-repo repo from /home/ubuntu/dent/poky/build/tmp/work/delta_tn48m-poky-linux/dentos-image/1.0/oe-rootfs-repo
User-Agent: falling back to 'libdnf': could not detect OS or basearch
repo: using cache for: oe-repo
oe-repo: using metadata from Thu 21 Aug 2025 07:23:46 AM UTC.
--> Starting dependency resolution
--> Finished dependency resolution
Error:
 Problem: conflicting requests
  - nothing provides poed needed by packagegroup-dentos-1.0-r0.delta_tn48m from oe-repo
(try to add '--skip-broken' to skip uninstallable packages)

Fix this by actually provide a working recipe:

* do checkout including submodules
* add missing dependencies
* actually install files, and install them to the expected locations

[jonas.gorski: split out poed changes, write commit log]
Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>